# -*- coding: utf-8 -*-
"""homework(numpy).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXPtJpUA6_LqCG6Nz443Z7Ieh8PlycQe
"""

import numpy as np

A = np.matrix([[1,-1],
               [2, 1]])

A

A**2-2*A+3

b = np.matrix([[-1], [2]])
b

x = np.linalg.solve(A, b)
x

A*x

Ainv = np.linalg.inv(A)
Ainv

A*Ainv

np.linalg.det(A)

